cqse/teamscale-profiler-dotnet

Profiler/CProfilerCallback.cpp, Profiler_Test/ProfilerTest.cs
=> Log command line

UploadDaemon/UploadDaemon.csproj, UploadDaemon/nlog.config
=> make upload daemon an windows application to prevent console

UploadDaemon/App.config, documentation/userguide.md
=> add examples for disabling proxy settings to app.config

.gitignore, Settings.StyleCop
Not sure about your policy w.r.t. pushing directly to master, hence, a PR. Added the most recent StyleCop settings from the Teamscale repo and put the respective cache files on .gitignore, as it is done for Teamscale. Anything I missed?
=> Add StyleCop configuration.

Profiler/UploadDaemon.cpp
=> don't profile the upload daemon process

Examples/Profile 64-bit App.bat
=> Add example batch file for 64-bit application

UploadDaemon/Config.cs, UploadDaemon/UploadDaemon.json, documentation/userguide.md
=> add option to disable SSL certificate validation

Common/Config.cs, Common/ConfigParser.cs, UploadDaemon/TimerAction.cs, UploadDaemon_Test/Config/ConfigParserTest.cs, UploadDaemon_Test/Config/ConfigTest.cs, UploadDaemon_Test/TimerActionTest.cs, documentation/userguide.md
=> Assembly version prefix

documentation/userguide.md
=> Document profiling Azure apps

Common/Config.cs, Common/ConfigParser.cs, Profiler/Profiler.example.yml, UploadDaemon/UploadDaemon.cs, UploadDaemon_Test/Config/ConfigTest.cs, documentation/userguide.md
=> Make upload-interval configurable

Profiler/CClassFactory.cpp, Profiler/CProfilerCallback.cpp, Profiler/CProfilerCallback.h, Profiler/utils/Debug.cpp, Profiler/utils/Debug.h
=> Hanging process

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, README.md
=> add changelog and update documentation accordingly

.appveyor.yml
Addresses issue [TS-29387](https://jira.cqse.eu/browse/TS-29387)
=> Inconsistent latest version numbers

CHANGELOG.md, UploadDaemon/UploadDaemon.cs
Addresses issue [TS-29693](https://jira.cqse.eu/browse/TS-29693)
=> TS-29693: Prevent multiple upload daemon instances

documentation/userguide.md
Addresses issue [TS-30302](https://jira.cqse.eu/browse/TS-30302)
=> TS-30302 Replaced line coverage by method-accurate coverage in userguide

CHANGELOG.md, UploadDaemon/App.config, UploadDaemon/UploadDaemon.csproj, UploadDaemon/packages.config, UploadDaemon_Test/UploadDaemon_Test.csproj, UploadDaemon_Test/app.config, UploadDaemon_Test/packages.config
Addresses issue [TS-30815](https://jira.cqse.eu/browse/TS-30815)
=> TS-30815 Update Newtonsoft.JSON

CHANGELOG.md, UploadDaemon/Configuration/Artifactory.cs, UploadDaemon/Configuration/Config.cs, UploadDaemon/Configuration/ConfigParser.cs, UploadDaemon/Upload/ArtifactoryUpload.cs, UploadDaemon/Upload/HttpClientUtils.cs, UploadDaemon/Upload/UploadFactory.cs, UploadDaemon/UploadDaemon.csproj, documentation/userguide.md
Addresses issue [TS-30168](https://jira.cqse.eu/browse/TS-30168)
=> TS-30168 Standard Artifact Storage Schema for Artifactory

Profiler/Profiler.example.yml, Profiler_Test/ProfilerTest.cs, documentation/userguide.md
Addresses issue [PST-12](https://jira.cqse.eu/browse/PST-12)
=> PST-12 replace yaml block with flow style

Profiler/log/FileLogBase.cpp, Profiler/utils/WindowsUtils.cpp, Profiler/utils/WindowsUtils.h, UploadDaemon/Upload/FileSystemUpload.cs, documentation/userguide.md
Addresses issue [TS-33891](https://jira.cqse.eu/browse/TS-33891)
=> TS-33891 ensure target directories are created

UploadDaemon/Configuration/Config.cs, UploadDaemon/UploadDaemon.cs, documentation/userguide.md
Addresses issue [TS-33933](https://jira.cqse.eu/browse/TS-33933)
=> TS-33933 provide config file on startup

CHANGELOG.md, UploadDaemon/Configuration/TeamscaleServer.cs, UploadDaemon_Test/UploadDaemonSystemTest.cs
Addresses issue [TS-34296](https://cqse.atlassian.net/browse/TS-34396)
=> TS-34396 Handle trailing slash for upload

UploadDaemon/Configuration/Config.cs, UploadDaemon/Configuration/ConfigParser.cs, UploadDaemon/UploadTask.cs, UploadDaemon_Test/Configuration/ConfigParserTest.cs, UploadDaemon_Test/Configuration/ConfigTest.cs, documentation/userguide.md
Addresses issue [TS-33932](https://jira.cqse.eu/browse/TS-33932)
=> TS-33932 upload config based on loaded assemblies

CHANGELOG.md, Profiler/log/FileLogBase.cpp, Profiler/utils/WindowsUtils.cpp, Profiler/utils/WindowsUtils.h
Addresses issue [TS-35530](https://jira.cqse.eu/browse/TS-35530)
=> TS#35530 Check if the trace directory is writable

.github/workflows/actions.yml
Addresses issue [TS-XXXXX](https://jira.cqse.eu/browse/TS-XXXXX)
=> try fixing release pipeline

CHANGELOG.md, UploadDaemon/Upload/TeamscaleUpload.cs, UploadDaemon_Test/UploadDaemonSystemTest.cs
Addresses issue [TS-38867](https://jira.cqse.eu/browse/TS-38867)
=> TS-38867 Adjust Upload Daemon to new API endpoints
